[package]
authors = ["Terkwood <38859656+Terkwood@users.noreply.github.com>"]
description = "Track resentments, fears, etc in support of your 12-step program"
edition = "2018"
license = "MIT"
name = "inventory"
version = "0.0.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.67"
yew = "0.17.3"
web-sys = "0.3.44"
serde = "1.0.115"
serde_derive = "1.0.115"
serde_json = "1.0.57"
js-sys = "0.3.44"
